name: "King'ori Maina"
highlighter: rouge
permalink: /:categories/:year/:month/:title/
relative_permalinks: false

sass:
  sass_dir: _sass
  style: :compressed

exclude: [
  'CNAME',
  'Gemfile',
  'Gemfile.lock',
  'kingori.co.sublime-project',
  'README.md',
  'Rakefile',
  'vendor/'
]

markdown: kramdown
kramdown:
  input: GFM
  auto_id_prefix: ''
  auto_id_stripping: true
  auto_ids: true
  entity_output: as_char
  footnote_backlink: '&8617;'
  footnote_nr: 1
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
