name: "King'ori J. Maina"
markdown: redcarpet
pygments: true
permalink: /:categories/:year/:month/:title/

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

author:
  fullname: "King'ori J. Maina"
  email: "yo@kingori.co"
  github: "itsmrwave"
  github_url: "https://github.com/itsmrwave"
  googleplus: "+KingoriMaina"
  googleplus_url: "https://www.google.com/+KingoriMaina"
  linkedin: "jobkingori"
  linkedin_url: "https://ke.linkedin.com/in/jobkingori"
  twitter: "@itsmrwave"
  twitter_url: "https://twitter.com/itsmrwave"
