github:
  handle: itsmrwave
  url: https://github.com/itsmrwave
instagram:
  handle: itsmrwave
  url: https://instagram.com/itsmrwave
linkedin:
  handle: jobkingori
  url: https://ke.linkedin.com/in/jobkingori
twitter:
  handle: "@itsmrwave"
  url: https://twitter.com/itsmrwave
