github:
  handle: itskingori
  url: https://github.com/itskingori
instagram:
  handle: itskingori
  url: https://instagram.com/itskingori
linkedin:
  handle: kingorimaina
  url: https://ke.linkedin.com/in/kingorimaina
twitter:
  handle: "@itskingori"
  url: https://twitter.com/itskingori
