github:
  handle: itskingori
  url: https://github.com/itskingori
instagram:
  handle: itskingori
  url: https://instagram.com/itskingori
linkedin:
  handle: jobkingori
  url: https://ke.linkedin.com/in/jobkingori
twitter:
  handle: "@itsmrwave"
  url: https://twitter.com/itsmrwave
