name: test-application

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  html-proofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run HTML Proofer
        run: bundle exec rake html_proofer
